### Medical Assistant Bot - Multi-Agent Workflow

### Install package
# !pip install -q google-generativeai

### Import libraries
import google.generativeai as genai
from datetime import datetime
from google.colab import userdata
import os

### Configure API key
genai.configure(api_key=userdata.get('GOOGLEAPIKEY'))

### Load LLM Model
# Using a low temperature (0.3) to ensure precise, content-based medical answers
model = genai.GenerativeModel(
    model_name="gemini-flash-latest",
    generation_config={"temperature": 0.3}
)

### Create Agents

### Agent 1 - Health Risk Analyzer
def health_risk_agent(user_input):
    print("\n[Health Risk Analysis Agent]")
    prompt = f'''
    I am a medical assistant. Analyze the patient's health conditions and classify the health risk level (Low, Medium, High).
    - List the top 3 health concerns.
    - Keep the output concise to 3-4 lines only.

    Patient input:
    {user_input}
    '''
    response = model.generate_content(prompt)
    print(response.text)
    return response.text

### Agent 2 - Medical Suggestion Agent
def suggestion_agent(risk_summary):
    print("\n[Medical Suggestion Agent]")
    prompt = f'''
    I am a medical assistant.
    - Based on the health risk summary, suggest top 3 medical suggestions or lifestyle changes.
    - Keep the output concise to 3-4 lines only and in bullet points.

    Health Risk Summary:
    {risk_summary}
    '''
    response = model.generate_content(prompt)
    print(response.text)
    return response.text

### Agent 3 - Routing Agent
def routing_agent(medical_suggestions):
    print("\n[Routing Agent]")
    prompt = f'''
    I am a medical routing assistant.
    - Based on the medical suggestions, determine if the patient needs professional medical advice, medical-legal advice, or if they can simply use a homegrown prescription/remedy.
    - Provide the final routing decision and keep the output concise to 1-2 lines.

    Context:
    {medical_suggestions}
    '''
    response = model.generate_content(prompt)
    print(response.text)
    return response.text

### Agent 4 - Prescription & Logging Agent
def prescription_logger_agent(name, pid, input_text, risk, suggestions, routing):
    print("\n[Prescription Logger Agent] Printing and Saving Prescription...")
    log_entry = f'''
    Time: {datetime.now()}
    Patient Name: {name}
    Patient ID: {pid}

    Reported Health Conditions:
    {input_text}

    Health Risk Analysis:
    {risk}

    Medical Suggestions:
    {suggestions}

    Recommended Routing:
    {routing}
    '''

    # Utilizing the OS library to create and append to a local text file
    with open("medical_prescription_log.txt", "a") as f:
        f.write(log_entry)

    print("Prescription saved successfully to 'medical_prescription_log.txt'")


### Define User Input
name = input("Enter patient name: ")
pid = input("Enter patient ID: ")
user_input = input("Enter the patient's health conditions (e.g., age, symptoms, duration, current medications): ")

### Run Multi-Agent Pipeline (Dependent Linear Flow)
risk_summary = health_risk_agent(user_input)
medical_suggestions = suggestion_agent(risk_summary)
routing_decision = routing_agent(medical_suggestions)

# The final agent logs all the variables generated by the previous agents
prescription_logger_agent(name, pid, user_input, risk_summary, medical_suggestions, routing_decision)